# Generated by ChatGPT

import torch
import numpy as np
from PIL import Image, ImageDraw

def tensor_to_image_with_scale(tensor, filename="output_image_with_scale.png"):
    assert tensor.shape[0] == 2

    h, w = tensor.shape[1:]
    brightness = (1 - tensor[0]).clamp(0, 1)
    color_ratio = tensor[1].clamp(0, 1)

    red = (brightness * color_ratio * 255).to(torch.uint8).numpy()
    green = (brightness * (1 - color_ratio) * 255).to(torch.uint8).numpy()
    blue = torch.zeros((h, w), dtype=torch.uint8).numpy()

    img_array = np.stack((red, green, blue), axis=-1)
    img = Image.fromarray(img_array, 'RGB')

    scale_width = 20
    scale_img = Image.new("RGB", (scale_width, h))
    scale_draw = ImageDraw.Draw(scale_img)

    for y in range(h):
        scale_brightness = 1 - (y / h)
        scale_color = int(scale_brightness * 255)
        color = (scale_color, scale_color, scale_color)
        scale_draw.line([(0, y), (scale_width, y)], fill=color)

    combined_img = Image.new("RGB", (w + scale_width, h))
    combined_img.paste(img, (0, 0))
    combined_img.paste(scale_img, (w, 0))
    combined_img.save(filename)

